apps/views.py
import os
import sys
import ldap3
import mimetypes
from flask import (request,render_template,flash, redirect, url_for, Blueprint,abort,jsonify,send_file,session,g)
from flask_login import (current_user,login_user,logout_user,login_required)
from apps import app
from apps import login_manager
from apps.auth import User,LoginForm
from apps.fetch_url import fetchProjects
from apps.projects import getProjectsList
from apps.utils import write_file, dir_tree, get_file_extension
from apps.git_actions import deleteProject,pullProject,pushProject


FLASKCODE_APP_TITLE = 'Workflow Submission Application'
FLASKCODE_EDITOR_THEME = 'vs-dark'
FLASKCODE_RESOURCE_BASEPATH = None

auth = Blueprint('auth', __name__)

@auth.context_processor
def process_template_context():
    return dict(
        app_title=FLASKCODE_APP_TITLE,
        editor_theme=FLASKCODE_EDITOR_THEME
    )

@login_manager.user_loader

def load_user(id):
    return User

@auth.before_request
def get_current_user():
    g.user = current_user

@auth.route('/')
def main_index():
    if current_user.is_authenticated:
        return redirect('/home')

    else:
        return redirect('/login')


@auth.route('/login')
@auth.route('/authenticate', methods = ['POST'])

def login():
    if request.method == 'POST':
        form = LoginForm(request.form)
        username = request.form['username']
        password = request.form['password']

        try:
            User.try_login(username,password)
        except:
            flash(
                'Invalid username or password. Please try again.',
                'danger')
            return redirect('/login')

        user = User(username = username, password = password)
        login_user(user)
        session['Username'] = username
        current_user.username = username 
        return redirect('/home')

    else:
        form = LoginForm(request.form)
        return render_template('home/login.html', form=form) 


@auth.route('/home')
@login_required
def home():
    user = session['Username']
    if os.path.exists('/home/' + user + '/workflow_app_projects'):
        projects = getProjectsList('/home/' + user + '/workflow_app_projects')
    else:
        projects = []
    return render_template('home/index.html', projects=projects)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect('/login')


@auth.route('/fetch', methods = ['GET','POST'])
@login_required
def fetch_url():
    user=session['Username']
    username = request.form['username']
    password = request.form['password']
    url = request.form['url']

    output = fetchProjects(user, username, password, url)

    if output == 0:
        flash('Project has been fetched successfully', 'success')
    elif output == 1:
        flash('Invalid username or password. Please try again.', 'danger')
    elif output == 2:
        flash('Project url is incorrect. Please try again.', 'danger')
    elif output == 3:
        flash('Project already exits. Existing projects cannot be fetched again.', 'danger')
    elif output == 4:
        flash('Unexpected error. Please try again.', 'danger')

    return redirect('/home')


@auth.route('/delete', methods = ['GET','POST'])
@login_required
def delete_project():

    if request.method == 'POST':
        project = request.form['action']
        output = deleteProject(session['Username'], project) 
        if output == 0:
            flash('Project has been deleted successfully', 'success')    
        else:
            flash('An error occured while deleting project', 'danger') 

    return redirect('/home')

@auth.route('/pull', methods = ['GET','POST'])
@login_required
def pull_project():

    if request.method == 'POST':
        project = request.form['action']
        output = pullProject(session['Username'], project)
        if output == 0:
            flash('Project has been pulled successfully', 'success')
        else:
            flash('An error occured while pulling project', 'danger')

    return redirect('/home')

    
@auth.route('/push', methods = ['GET','POST'])
@login_required
def push_project():

    if request.method == 'POST':
        project = request.form['action']
        output = pushProject(session['Username'], project)
        if output == 0:
            flash('Project has been pushed successfully', 'success')
        else:
            flash('An error occured while pushing project', 'danger')

    return redirect('/home')


def get_segment( request ):
    try:
        segment = request.path.split('/')[-1]
        if segment == '':
            segment = 'index'
        return segment
    except:
        return None


@auth.route('/files', methods = ['GET','POST'])
@login_required
def index():
    user = session['Username']

    if request.method == 'POST':
        session['project'] = request.form['action']
    
    resource_basepath = '/home/' + user + '/workflow_app_projects/' + session['project'] 
    if not (resource_basepath and os.path.isdir(resource_basepath)):
        abort(500, '`FLASKCODE_RESOURCE_BASEPATH` is not a valid directory path')
    else:
        g.flaskcode_resource_basepath = os.path.abspath(resource_basepath).rstrip('/\\')

    dirname = os.path.basename(g.flaskcode_resource_basepath)
    dtree = dir_tree(g.flaskcode_resource_basepath, g.flaskcode_resource_basepath + '/')
    return render_template('flaskcode/index.html', dirname=dirname, dtree=dtree)


@auth.route('/resource-data/<path:file_path>.txt', methods=['GET', 'HEAD'])
@login_required
def resource_data(file_path):
    user = session['Username']
    resource_basepath = '/home/' + user + '/workflow_app_projects/' + session['project'] 
    if not (resource_basepath and os.path.isdir(resource_basepath)):
        abort(500, '`FLASKCODE_RESOURCE_BASEPATH` is not a valid directory path')
    else:
        g.flaskcode_resource_basepath = os.path.abspath(resource_basepath).rstrip('/\\')

    file_path = os.path.join(g.flaskcode_resource_basepath, file_path)
    if not (os.path.exists(file_path) and os.path.isfile(file_path)):
        abort(404)
    response = send_file(file_path, mimetype='text/plain', cache_timeout=0)
    mimetype, encoding = mimetypes.guess_type(file_path, False)
    if mimetype:
        response.headers.set('X-File-Mimetype', mimetype)
        extension = mimetypes.guess_extension(mimetype, False) or get_file_extension(file_path)
        if extension:
            response.headers.set('X-File-Extension', extension.lower().lstrip('.'))
    if encoding:
        response.headers.set('X-File-Encoding', encoding)
    return response


@auth.route('/update-resource-data/<path:file_path>', methods=['POST'])
@login_required
def update_resource_data(file_path):
    user = session['Username']
    resource_basepath = '/home/' + user + '/workflow_app_projects/' + session['project'] 
    if not (resource_basepath and os.path.isdir(resource_basepath)):
        abort(500, '`FLASKCODE_RESOURCE_BASEPATH` is not a valid directory path')
    else:
        g.flaskcode_resource_basepath = os.path.abspath(resource_basepath).rstrip('/\\')

    file_path = os.path.join(g.flaskcode_resource_basepath, file_path)
    is_new_resource = bool(int(request.form.get('is_new_resource', 0)))
    if not is_new_resource and not (os.path.exists(file_path) and os.path.isfile(file_path)):
        abort(404)
    success = True
    message = 'File saved successfully'
    resource_data = request.form.get('resource_data', None)
    if resource_data:
        success, message = write_file(resource_data, file_path)
    else:
        success = False
        message = 'File data not uploaded'
    return jsonify({'success': success, 'message': message})

apps/templates/flaskcode/_base.html
<!doctype html>
<html{% block html_attrs %} lang="en"{% endblock %}>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <meta name="robots" content="noindex, nofollow" />
    <title>{% block page_title %}{{ app_title }}{% endblock %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}" />
    <meta name="theme-color" content="#222" />

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" />
    {% block page_styles %}{% endblock %}

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body{% block body_attrs %}{% endblock %}>
    {% block page_body %}
    <div id="page-preloader" class="page-preloader">
        <div class="loading-center">
            <div class="loading-center-absolute">
                <i class="fa fa-spinner fa-pulse" aria-hidden="true"></i>
                <br />
                <i class="fa fa-code" aria-hidden="true"></i> {{ app_title }}
                <small><em>v{{ app_version }}</em></small>
            </div>
        </div>
    </div>

    <div id="wrapper">
    <!-- header -->
    {% include 'flaskcode/_header.html' %}
    <!-- /header -->

    <div id="page-wrapper">
        <!-- .container -->
        <div id="page-container" class="container-fluid">
            <!-- page-content -->
            {% block page_content %}{% endblock %}
            <!-- /page-content -->
        </div>
        <!-- /.container -->
    </div>

    <!-- footer -->
    {% include 'flaskcode/_footer.html' %}
    <!-- /footer -->
    </div>
    {% endblock %}

    <script type="text/javascript" src="{{ url_for('static', filename='vendor/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
    {% block page_scripts %}{% endblock %}
</body>
</html>

apps/templates/flaskcode/_footer.html
<footer id="page-footer">
    <span class="hidden-xs"><i class="fa fa-folder" aria-hidden="true"></i> {{ dirname }}</span>
    <span class="pull-right">
        <span id="editor_lang" title="Detected Language"></span>&nbsp;&nbsp;&nbsp;Ln&nbsp;<span id="line_num"></span>,&nbsp;Col&nbsp;<span id="column_num"></span>
    </span>
</footer>

apps/templates/flaskcode/_header.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand brand-logo" href="{{ url_for('auth.index') }}"><i class="fa fa-code" aria-hidden="true"></i> {{ app_title }}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/"><i class="fa fa-fw fa-chevron-left" aria-hidden="true"></i> Home</a></li>
            </ul>
        </div>
    </div>
</nav>

apps/templates/flaskcode/_macros.html
{# render dir tree in recursive list #}
{% macro render_dir_tree(dir_tree, tree_id) %}
    <ul id="{{ tree_id }}">
        {%- for item in dir_tree.children recursive %}
        <li class="resource-items{% if item.is_file %} file-item{% elif not item.children %} disabled{% else %} dir-item{% endif %}"
            title="{{ item.name }}"
            data-path-name="{{ item.path_name }}"
            data-url="{{ url_for('auth.resource_data', file_path=item.path_name) }}">
            {{ item.name }}
            {%- if item.children -%}
            <ul>{{ loop(item.children) }}</ul>
            {%- endif %}
        </li>
        {%- endfor %}
    </ul>
{% endmacro %}

apps/templates/flaskcode/index.html
{% extends 'flaskcode/_base.html' %}
{% from 'flaskcode/_macros.html' import render_dir_tree %}

{% block page_title %}{{ app_title }} - {{ dirname }}{% endblock %}

{% block page_content %}
    <!--Modals-->
    <div id="fileNameModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="fileNameModalLabel">
        <div class="modal-dialog modal-md" role="document">
            <div class="modal-content">
                <form id="fileNameForm" method="post">
                    <input type="hidden" id="base_url" name="base_url" value="" />
                    <input type="hidden" id="base_path_name" name="base_path_name" value="" />
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="fileNameModalLabel">Create New File</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="new_filename" class="control-label">New File:</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><span class="base-path-name"></span>/</div>
                                        <input type="text" class="form-control" id="new_filename" name="new_filename" placeholder="New File Name" required />
                                    </div>
                                    <span class="form-msg" class="help-block"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" data-loading-text="Loading...">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--/Modals-->

    <div id="page-row" class="row">
        <div id="flaskcode-list" class="col-md-2 col-sm-3 col-xs-3">
            <!-- <h4 style="white-space:nowrap;"><i class="fa fa-folder" aria-hidden="true"></i> {{ dirname|truncate(20) }}</h4> -->
            <div class="list-header well well-sm mb-0"><i class="fa fa-folder" aria-hidden="true"></i> {{ dirname|truncate(20) }}</div>
            <div class="list-container">
                {{ render_dir_tree(dtree, 'dir-tree') }}
            </div>
        </div>
        <div id="flaskcode-content" class="col-md-10 col-sm-9 col-xs-9">
            <div id="editor-header" class="editor-header well well-sm mb-0">
                <!-- <strong><i class="fa fa-code" aria-hidden="true"></i> {{ app_title }}</strong> -->
                &nbsp;
                <span id="resource-info">
                    <a href="javascript:void(0);" id="resource-close" class="text-danger" title="Close" style="display:none;"><i class="fa fa-window-close" aria-hidden="true"></i></a>
                    <span id="resource-name" title=""></span>
                    <i id="resource-mod" class="text-danger fa fa-asterisk" aria-hidden="true" style="display:none;"></i>
                </span>
                <span class="pull-right hidden-xs" id="header-action-group">
                    <a href="javascript:void(0);" class="header-actions" data-action-id="save" title="Save"><span class="badge badge-primary"><i class="fa fa-save" aria-hidden="true"></i> Save</span></a>
                    &nbsp;|&nbsp;
                    <a href="javascript:void(0);" class="header-actions" data-action-id="reload" title="Reload"><span class="badge badge-primary"><i class="fa fa-refresh" aria-hidden="true"></i> Reload</span></a>
                    &nbsp;|&nbsp;
                    <a href="javascript:void(0);" class="header-actions" data-action-id="force-reload" title="Force Reload"><span class="badge badge-danger"><i class="fa fa-retweet" aria-hidden="true"></i></span></a>
                    &nbsp;|&nbsp;
                    <a href="javascript:void(0);" id="toggle-minimap" title="Toggle Minimap"><span class="badge badge-primary"><i class="fa fa-th-list" aria-hidden="true"></i></span></a>
                </span>
            </div>
            <!-- Editor Widget -->
            <div id="editor-container" class="editor-container{% if editor_theme == 'vs' %} light-theme{% endif %}">
                <div class="editor-preloader" style="display:none;">
                    <div class="loading-center">
                        <div class="loading-center-absolute">Requesting...</div>
                    </div>
                </div>
                <div class="editor-notification text-center"></div>
                <div class="editor-body">
                    <div class="editor-body-msg">
                        <h2 class="text-center text-info"><i class="fa fa-code" aria-hidden="true"></i> {{ app_title }}</h2>
                    </div>
                </div>
            </div>
            <!-- /Editor Widget -->
        </div>
    </div>
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/font-awesome/css/font-awesome.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/jquery-contextMenu/jquery.contextMenu.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/treed/treed.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" />
{% endblock %}

{% block page_scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='vendor/jquery-contextMenu/jquery.contextMenu.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='vendor/monaco-editor/min/vs/loader.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='vendor/treed/treed.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/objects.js') }}"></script>
<script type="text/javascript">
flaskcode.config.set('pluginsBaseUrl', "{{ url_for('static', filename='vendor') }}");
flaskcode.config.set('updateResourceBaseUrl', "{{ url_for('auth.update_resource_data', file_path='') }}");
flaskcode.config.set('resourceUrlTemplate', "{{ url_for('auth.resource_data', file_path='__pathname__') }}");
flaskcode.config.set('editorTheme', "{{ editor_theme }}");
</script>
<script type="text/javascript" src="{{ url_for('static', filename='js/flaskcode.js') }}"></script>
{% endblock %}